d/shuffle-binaries: Make error detection/message overt
The reason for the `ls` at the end is pretty straightforward if you think
about it, mainly confirming the shuffle step did something.  Yet that
is a bit non-obvious, and the error message produced on failure is poor
("No such file or directory" simply means the script failed somewhere?).
Add an overt error message.

Signed-off-by: Elliott Mitchell <ehem+debian@m5p.com>
Acked-by: Hans van Kranenburg <hans@knorrie.org>

diff --git a/debian/shuffle-binaries b/debian/shuffle-binaries
--- a/debian/shuffle-binaries
+++ b/debian/shuffle-binaries
@@ -47,4 +47,7 @@ for binary in `find $t/usr/{bin,sbin} -type f`; do
 	)
 done
 
-ls debian/shuffle-binaries.stamp
+if [ ! -e "$0.stamp" ]; then
+	echo "Failed to shuffle binaries!" 1>&2
+	exit 1
+fi
